"""
Mock generation provider.

Used for testing the generation pipeline without
external LLM providers.
"""

from __future__ import annotations

from core.models.generation import ProviderType

from .base import BaseProvider


class MockProvider(BaseProvider):
    """
    Fake provider implementation.

    Returns deterministic responses for testing.
    """

    def __init__(
        self,
        response: str | None = None,
    ) -> None:
        """
        Initialize mock provider.

        Args:
            response:
                Optional predefined response.
        """

        self._response = response

    # =========================================================
    # Public API
    # =========================================================

    def generate(
        self,
        prompt: str,
    ) -> str:
        """
        Generate a mock response.

        Args:
            prompt:
                Rendered generation prompt.

        Returns:
            Mock LLM response.
        """

        if self._response:
            return self._response

        return self._default_response(
            prompt
        )

    # =========================================================
    # Helpers
    # =========================================================

    @staticmethod
    def _default_response(
        prompt: str,
    ) -> str:
        """
        Generate deterministic mock output.
        """

        return f"""
FILE:
generated/mock_output.py

CODE:
# Generated by MockProvider

def generated_function():
    return "CodePilot AI"

# Prompt length:
# {len(prompt)}
"""