from datetime import datetime
from typing import Dict, List

from pydantic import BaseModel, Field


# ============================================================
# Repository Models
# ============================================================


class RepositoryInfo(BaseModel):
    """
    Metadata about the repository discovered during exploration.
    """

    language: str = Field(
        default="Unknown",
        description="Primary programming language.",
    )

    framework: str = Field(
        default="Unknown",
        description="Detected framework.",
    )

    database: str = Field(
        default="Unknown",
        description="Detected database.",
    )

    package_manager: str = Field(
        default="Unknown",
        description="Detected package manager.",
    )

    files: List[str] = Field(
        default_factory=list,
        description="Important repository files.",
    )

    total_files: int = Field(
        default=0,
        description="Total number of scanned files.",
    )


# ============================================================
# Planner Models
# ============================================================


class Plan(BaseModel):
    """
    Structured implementation plan generated by the LLM.
    """

    goal: str = Field(
        ...,
        description="Overall implementation goal.",
    )

    relevant_files: List[str] = Field(
        default_factory=list,
        description="Files that should be read or modified.",
    )

    implementation_steps: List[str] = Field(
        default_factory=list,
        description="Implementation steps.",
    )

    risks: List[str] = Field(
        default_factory=list,
        description="Potential implementation risks.",
    )

    testing: List[str] = Field(
        default_factory=list,
        description="Testing checklist.",
    )


# ============================================================
# Reader Models
# ============================================================


class RepositoryContext(BaseModel):
    """
    Source code loaded from the repository.
    """

    files: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of file path to file contents.",
    )

    loaded_files: List[str] = Field(
        default_factory=list,
        description="Successfully loaded files.",
    )

    missing_files: List[str] = Field(
        default_factory=list,
        description="Files requested by the planner but not found.",
    )

    skipped_files: List[str] = Field(
        default_factory=list,
        description="Binary, unreadable or oversized files.",
    )


# ============================================================
# Coder Models
# ============================================================


class GeneratedFile(BaseModel):
    """
    A generated or modified file.
    """

    path: str = Field(
        ...,
        description="Repository-relative file path.",
    )

    content: str = Field(
        ...,
        description="Complete updated file content.",
    )


class CodeResponse(BaseModel):
    """
    Response returned by the coding model.
    """

    files: List[GeneratedFile] = Field(
        default_factory=list,
        description="Files generated or modified.",
    )


# ============================================================
# Executor Models
# ============================================================


class ExecutionResult(BaseModel):
    """
    Result after writing generated files.
    """

    written_files: List[str] = Field(
        default_factory=list,
        description="Files successfully written.",
    )

    failed_files: List[str] = Field(
        default_factory=list,
        description="Files that failed to write.",
    )


# ============================================================
# Summarizer Models
# ============================================================


class Summary(BaseModel):
    """
    Final execution summary.
    """

    files_changed: List[str] = Field(
        default_factory=list,
        description="Files modified during execution.",
    )

    features_added: List[str] = Field(
        default_factory=list,
        description="Features implemented.",
    )

    testing: List[str] = Field(
        default_factory=list,
        description="Recommended testing steps.",
    )

    notes: List[str] = Field(
        default_factory=list,
        description="Additional implementation notes.",
    )


# ============================================================
# Verification Models
# ============================================================


class DependencyReport(BaseModel):
    """
    Repository dependency and build configuration.
    """

    language: str = Field(
        default="Unknown",
        description="Detected programming language.",
    )

    framework: str = Field(
        default="Unknown",
        description="Detected application framework.",
    )

    package_manager: str = Field(
        default="Unknown",
        description="Detected package manager.",
    )

    install_command: str | None = Field(
        default=None,
        description="Command used to install project dependencies.",
    )

    build_command: str | None = Field(
        default=None,
        description="Command used to build the project.",
    )

    run_command: str | None = Field(
        default=None,
        description="Command used to start the project.",
    )

    detected_files: List[str] = Field(
        default_factory=list,
        description="Configuration files used during detection.",
    )

    warnings: List[str] = Field(
        default_factory=list,
        description="Repository warnings.",
    )


class BuildResult(BaseModel):
    """
    Result of building the project.
    """

    success: bool = False

    command: str = ""

    exit_code: int = 0

    duration: float = 0.0

    logs: str = ""

    errors: List[str] = Field(
        default_factory=list,
    )


class RuntimeResult(BaseModel):
    """
    Result of starting the application.
    """

    success: bool = False

    command: str = ""

    duration: float = 0.0

    logs: str = ""

    errors: List[str] = Field(
        default_factory=list,
    )


class DiscoveredRoute(BaseModel):
    """
    Route discovered before API testing.
    """

    method: str

    path: str

    source_file: str


class ApiEndpoint(BaseModel):
    """
    Result of testing a single API endpoint.
    """

    method: str

    path: str

    status_code: int | None = None

    response_time: float | None = None

    passed: bool = False

    error: str | None = None


class ApiTestResult(BaseModel):
    """
    API testing report.
    """

    total: int = 0

    passed: int = 0

    failed: int = 0

    duration: float = 0.0

    endpoints: List[ApiEndpoint] = Field(
        default_factory=list,
    )


class RootCause(BaseModel):
    """
    AI-generated root cause analysis.
    """

    summary: str = ""

    probable_causes: List[str] = Field(
        default_factory=list,
    )

    suggested_fixes: List[str] = Field(
        default_factory=list,
    )

    confidence: float = 0.0


class EngineeringReport(BaseModel):
    """
    Final engineering report produced after the entire pipeline.
    """

    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
    )

    repository: RepositoryInfo | None = None

    dependency: DependencyReport | None = None

    build: BuildResult | None = None

    runtime: RuntimeResult | None = None

    api: ApiTestResult | None = None

    root_cause: RootCause | None = None

    summary: Summary | None = None