from typing import Dict, List

from pydantic import BaseModel, Field


# ============================================================
# Planner Models
# ============================================================

class Plan(BaseModel):
    """
    Structured implementation plan generated by the LLM.
    """

    goal: str = Field(
        ...,
        description="Overall implementation goal."
    )

    relevant_files: List[str] = Field(
        default_factory=list,
        description="Files that should be read or modified."
    )

    implementation_steps: List[str] = Field(
        default_factory=list,
        description="Implementation steps."
    )

    risks: List[str] = Field(
        default_factory=list,
        description="Potential implementation risks."
    )

    testing: List[str] = Field(
        default_factory=list,
        description="Testing checklist."
    )


# ============================================================
# Reader Models
# ============================================================

class RepositoryContext(BaseModel):
    """
    Source code loaded from the repository.
    """

    files: Dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of file path to file contents."
    )

    loaded_files: List[str] = Field(
        default_factory=list,
        description="Successfully loaded files."
    )

    missing_files: List[str] = Field(
        default_factory=list,
        description="Files requested by the planner but not found."
    )

    skipped_files: List[str] = Field(
        default_factory=list,
        description="Binary, unreadable, or oversized files."
    )


# ============================================================
# Coder Models
# ============================================================

class GeneratedFile(BaseModel):
    """
    A single generated or modified file.
    """

    path: str = Field(
        ...,
        description="Repository-relative file path."
    )

    content: str = Field(
        ...,
        description="Complete updated file content."
    )


class CodeResponse(BaseModel):
    """
    Response returned by the coding model.
    """

    files: List[GeneratedFile] = Field(
        default_factory=list,
        description="Files generated or modified."
    )


# ============================================================
# Executor Models
# ============================================================

class ExecutionResult(BaseModel):
    """
    Result after writing generated files to disk.
    """

    written_files: List[str] = Field(
        default_factory=list,
        description="Files successfully written."
    )

    failed_files: List[str] = Field(
        default_factory=list,
        description="Files that failed to write."
    )


# ============================================================
# Summarizer Models
# ============================================================

class Summary(BaseModel):
    """
    Final execution summary.
    """

    files_changed: List[str] = Field(
        default_factory=list,
        description="Files modified during execution."
    )

    features_added: List[str] = Field(
        default_factory=list,
        description="Features implemented."
    )

    testing: List[str] = Field(
        default_factory=list,
        description="Recommended testing steps."
    )

    notes: List[str] = Field(
        default_factory=list,
        description="Additional implementation notes."
    )


class GeneratedFile(BaseModel):
    """
    A single generated or modified file.
    """

    path: str = Field(
        ...,
        description="Repository-relative file path."
    )

    content: str = Field(
        ...,
        description="Complete file contents."
    )


class CodeResponse(BaseModel):
    """
    Response produced by the coding model.
    """

    files: List[GeneratedFile] = Field(
        default_factory=list
    )


class ExecutionResult(BaseModel):
    """
    Result after writing files.
    """

    written_files: List[str] = Field(
        default_factory=list
    )

    failed_files: List[str] = Field(
        default_factory=list
    )


class Summary(BaseModel):
    """
    Final execution summary.
    """

    files_changed: List[str] = Field(
        default_factory=list
    )

    features_added: List[str] = Field(
        default_factory=list
    )

    testing: List[str] = Field(
        default_factory=list
    )

    notes: List[str] = Field(
        default_factory=list
    )    