import re
from typing import List


class FileSelector:
    """
    Extract relevant repository files from the
    implementation plan generated by the Planner.
    """

    FILE_PATTERN = re.compile(
        r'([A-Za-z0-9_\-/]+\.[A-Za-z0-9]+)'
    )

    def __init__(self, repository_files: List[str]):
        self.repository_files = set(repository_files)

    def extract(self, plan: str) -> List[str]:
        """
        Extract valid repository files mentioned
        in the implementation plan.
        """

        matches = self.FILE_PATTERN.findall(plan)

        selected = []

        seen = set()

        for file in matches:

            file = file.strip()

            if file in self.repository_files:

                if file not in seen:
                    selected.append(file)
                    seen.add(file)

        return selected