"""
Generation domain models.

These models define the immutable domain objects shared throughout the
Generation package. They represent the contract between the Planning,
Generation, Verification, and Execution stages of the CodePilot AI pipeline.

The models in this module contain no business logic. They only describe
the structure of the data exchanged between components.
"""

from __future__ import annotations

from enum import StrEnum
from pathlib import PurePosixPath
from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator


# ============================================================================
# Enums
# ============================================================================


class GenerationStatus(StrEnum):
    """
    Represents the lifecycle state of a generation request.
    """

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class ProviderType(StrEnum):
    """
    Supported code generation providers.
    """

    OPENAI = "openai"

    ANTHROPIC = "anthropic"

    OLLAMA = "ollama"

    CEREBRAS = "cerebras"

    MOCK = "mock"


class FileOperation(StrEnum):
    """
    Operation performed on a repository file.
    """

    CREATE = "create"
    UPDATE = "update"
    DELETE = "delete"


class ProgrammingLanguage(StrEnum):
    """
    Supported primary programming languages.
    """

    PYTHON = "python"
    TYPESCRIPT = "typescript"
    RUST = "rust"
    JAVA = "java"


class ProjectType(StrEnum):
    """
    Detected high-level project categories.
    """

    WEB = "web"
    BACKEND = "backend"
    CLI = "cli"
    LIBRARY = "library"
    MOBILE = "mobile"


class TaskPriority(StrEnum):
    """
    Priority levels for implementation tasks.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class TaskComplexity(StrEnum):
    """
    Estimated complexity of an implementation task.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


# ============================================================================
# Base Model
# ============================================================================


class ImmutableModel(BaseModel):
    """
    Base class for immutable domain models.
    """

    model_config = ConfigDict(
        frozen=True,
        extra="forbid",
        validate_assignment=False,
        use_enum_values=True,
    )


# ============================================================================
# Context Models
# ============================================================================


class RepositoryContext(ImmutableModel):
    """
    Snapshot of repository-level information used during generation.
    """

    name: str = Field(
        ...,
        description="Repository name.",
    )

    root_path: str = Field(
        ...,
        description="Repository root directory.",
    )

    project_type: ProjectType = Field(
        ...,
        description="Detected project type.",
    )

    primary_language: ProgrammingLanguage = Field(
        ...,
        description="Primary programming language.",
    )

    frameworks: list[str] = Field(
        default_factory=list,
        description="Detected frameworks.",
    )

    entry_points: list[str] = Field(
        default_factory=list,
        description="Repository entry points.",
    )

    source_directories: list[str] = Field(
        default_factory=list,
        description="Source code directories.",
    )

    ignored_directories: list[str] = Field(
        default_factory=list,
        description="Ignored directories.",
    )

    repository_files: list[str] = Field(
        default_factory=list,
        description="List of repository file paths (relative).",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional repository metadata.",
    )


class ProjectContext(ImmutableModel):
    """
    Snapshot of the project generated by the Planning stage.
    """

    name: str = Field(
        ...,
        description="Project name.",
    )

    summary: str = Field(
        ...,
        description="Project summary.",
    )

    objective: str = Field(
        ...,
        description="Overall project objective.",
    )

    architecture: str = Field(
        default="",
        description="Architecture overview.",
    )

    coding_standards: list[str] = Field(
        default_factory=list,
        description="Coding conventions.",
    )

    constraints: list[str] = Field(
        default_factory=list,
        description="Implementation constraints.",
    )

    assumptions: list[str] = Field(
        default_factory=list,
        description="Planning assumptions.",
    )

    relevant_files: list[str] = Field(
        default_factory=list,
        description="Files relevant to generation.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional project metadata.",
    )


class TaskContext(ImmutableModel):
    """
    Represents a single implementation task.
    """

    id: str = Field(
        ...,
        description="Unique task identifier.",
    )

    title: str = Field(
        ...,
        description="Task title.",
    )

    description: str = Field(
        ...,
        description="Task description.",
    )

    priority: TaskPriority = Field(
        default=TaskPriority.MEDIUM,
        description="Task priority.",
    )

    complexity: TaskComplexity = Field(
        default=TaskComplexity.MEDIUM,
        description="Estimated implementation complexity.",
    )

    acceptance_criteria: list[str] = Field(
        default_factory=list,
        description="Acceptance criteria.",
    )

    dependencies: list[str] = Field(
        default_factory=list,
        description="Task dependencies.",
    )

    relevant_files: list[str] = Field(
        default_factory=list,
        description="Files required for implementation.",
    )

    notes: list[str] = Field(
        default_factory=list,
        description="Additional implementation notes.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional task metadata.",
    )


class DependencyContext(ImmutableModel):
    """
    Dependency information required during generation.
    """

    internal_modules: list[str] = Field(
        default_factory=list,
        description="Internal project modules.",
    )

    external_packages: list[str] = Field(
        default_factory=list,
        description="External dependencies.",
    )

    related_files: list[str] = Field(
        default_factory=list,
        description="Files related to the current task.",
    )

    imports: list[str] = Field(
        default_factory=list,
        description="Required imports.",
    )

    dependency_graph: dict[str, list[str]] = Field(
        default_factory=dict,
        description="Simplified dependency graph.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional dependency metadata.",
    )


# ============================================================================
# Generation Context
# ============================================================================


class GenerationContext(ImmutableModel):
    """
    Complete immutable context required to generate source code.

    This model acts as the contract between the Planning and Generation
    stages. Every component in the Generation package should operate on
    this model instead of receiving individual parameters.

    Retry / attempt state is intentionally omitted — that belongs to
    the execution or generator layer, not the generation context.
    """

    repository: RepositoryContext = Field(
        ...,
        description="Repository context.",
    )

    project: ProjectContext = Field(
        ...,
        description="Project context.",
    )

    task: TaskContext = Field(
        ...,
        description="Current implementation task.",
    )

    dependencies: DependencyContext = Field(
        ...,
        description="Dependency information.",
    )

    target_files: list[str] = Field(
        default_factory=list,
        description="Files expected to be created or modified.",
    )

    read_only_files: list[str] = Field(
        default_factory=list,
        description="Files that must never be modified.",
    )

    additional_instructions: list[str] = Field(
        default_factory=list,
        description="Extra instructions supplied to the generator.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional generation metadata.",
    )

    @property
    def frameworks(self) -> list[str]:
        """
        Shortcut to repository frameworks.
        """
        return self.repository.frameworks

    @property
    def language(self) -> ProgrammingLanguage | str:
        """
        Primary project language.
        """
        return self.repository.primary_language

    @property
    def project_name(self) -> str:
        """
        Project name.
        """
        return self.project.name

    @property
    def task_title(self) -> str:
        """
        Current task title.
        """
        return self.task.title

    @property
    def task_description(self) -> str:
        """
        Current task description.
        """
        return self.task.description


# ============================================================================
# Output Models
# ============================================================================


class GeneratedFile(ImmutableModel):
    """
    Represents a file generated or modified during code generation.
    """

    path: str = Field(
        ...,
        description="Repository-relative file path.",
    )

    language: str = Field(
        ...,
        description="Programming language of the file contents.",
    )

    operation: FileOperation = Field(
        default=FileOperation.CREATE,
        description="Operation performed on the file.",
    )

    content: str = Field(
        ...,
        description="Complete file contents.",
    )

    reason: str | None = Field(
        default=None,
        description="Reason why the file was generated or modified.",
    )

    checksum: str | None = Field(
        default=None,
        description="Optional content checksum (e.g. SHA-256).",
    )

    size: int = Field(
        default=0,
        ge=0,
        description="Content size in bytes.",
    )

    encoding: str = Field(
        default="utf-8",
        description="Text encoding used for the file.",
    )

    newline: str = Field(
        default="\n",
        description="Newline convention used in the file.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional file metadata.",
    )

    @property
    def is_new_file(self) -> bool:
        """Whether the file is newly created."""
        return self.operation == FileOperation.CREATE

    @property
    def is_modified(self) -> bool:
        """Whether the file updates an existing file."""
        return self.operation == FileOperation.UPDATE

    @property
    def is_deleted(self) -> bool:
        """Whether the file should be deleted."""
        return self.operation == FileOperation.DELETE

    @property
    def filename(self) -> str:
        """Return the filename without directories."""
        return PurePosixPath(self.path).name

    @property
    def extension(self) -> str:
        """Return the file extension (including the leading dot)."""
        return PurePosixPath(self.path).suffix


class GenerationStatistics(ImmutableModel):
    """
    Statistics collected during generation.
    """

    files_created: int = Field(default=0, ge=0)
    files_updated: int = Field(default=0, ge=0)
    files_deleted: int = Field(default=0, ge=0)

    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)

    generation_time: float = Field(
        default=0.0,
        ge=0.0,
        description="Generation time in seconds.",
    )

    @model_validator(mode="after")
    def validate_token_totals(self) -> Self:
        expected = self.prompt_tokens + self.completion_tokens
        if self.total_tokens != expected:
            raise ValueError(
                f"total_tokens ({self.total_tokens}) must equal "
                f"prompt_tokens + completion_tokens ({expected})"
            )
        return self

    @property
    def total_files(self) -> int:
        return (
            self.files_created
            + self.files_updated
            + self.files_deleted
        )


class GenerationResult(ImmutableModel):
    """
    Final output returned by the Generation package.
    """

    success: bool = Field(
        ...,
        description="Whether generation completed successfully.",
    )

    status: GenerationStatus = Field(
        default=GenerationStatus.COMPLETED,
        description="Generation status.",
    )

    provider: ProviderType = Field(
        ...,
        description="Provider used for generation.",
    )

    files: list[GeneratedFile] = Field(
        default_factory=list,
        description="Generated files.",
    )

    warnings: list[str] = Field(
        default_factory=list,
        description="Generation warnings.",
    )

    errors: list[str] = Field(
        default_factory=list,
        description="Generation errors.",
    )

    statistics: GenerationStatistics = Field(
        default_factory=GenerationStatistics,
        description="Generation statistics.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata.",
    )

    @model_validator(mode="after")
    def validate_status_consistency(self) -> Self:
        if self.success and self.status == GenerationStatus.FAILED:
            raise ValueError(
                "success=True is inconsistent with status=FAILED"
            )
        if not self.success and self.status not in (
            GenerationStatus.FAILED,
            GenerationStatus.PENDING,
            GenerationStatus.RUNNING,
        ):
            raise ValueError(
                "success=False requires a non-COMPLETED status "
                f"(got {self.status!r})"
            )
        return self

    @classmethod
    def success_result(
        cls,
        provider: ProviderType,
        files: list[GeneratedFile] | None = None,
        warnings: list[str] | None = None,
        statistics: GenerationStatistics | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> GenerationResult:
        """
        Factory for a successful generation result.
        """
        return cls(
            success=True,
            status=GenerationStatus.COMPLETED,
            provider=provider,
            files=files or [],
            warnings=warnings or [],
            errors=[],
            statistics=statistics or GenerationStatistics(),
            metadata=metadata or {},
        )

    @classmethod
    def failure_result(
        cls,
        provider: ProviderType,
        errors: list[str],
        files: list[GeneratedFile] | None = None,
        warnings: list[str] | None = None,
        statistics: GenerationStatistics | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> GenerationResult:
        """
        Factory for a failed generation result.
        """
        return cls(
            success=False,
            status=GenerationStatus.FAILED,
            provider=provider,
            files=files or [],
            warnings=warnings or [],
            errors=errors,
            statistics=statistics or GenerationStatistics(),
            metadata=metadata or {},
        )

    @property
    def generated_files(self) -> list[GeneratedFile]:
        return [
            file
            for file in self.files
            if file.operation == FileOperation.CREATE
        ]

    @property
    def modified_files(self) -> list[GeneratedFile]:
        return [
            file
            for file in self.files
            if file.operation == FileOperation.UPDATE
        ]

    @property
    def deleted_files(self) -> list[GeneratedFile]:
        return [
            file
            for file in self.files
            if file.operation == FileOperation.DELETE
        ]

    @property
    def file_count(self) -> int:
        return len(self.files)

    @property
    def has_errors(self) -> bool:
        return bool(self.errors)

    @property
    def has_warnings(self) -> bool:
        return bool(self.warnings)


class CodeResponse(GenerationResult):
    """
    Backwards-compatible alias for older interfaces.

    New components should use GenerationResult directly.
    """

    pass