"""
Generation domain models.

These models represent source code generated by the code generation stage of
the CodePilot AI pipeline.
"""

from typing import List

from pydantic import BaseModel, Field


class GeneratedFile(BaseModel):
    """
    A generated or modified repository file.
    """

    path: str = Field(
        ...,
        description="Repository-relative file path.",
    )

    content: str = Field(
        ...,
        description="Complete file contents.",
    )


class CodeResponse(BaseModel):
    """
    Response returned by the code generation stage.
    """

    files: List[GeneratedFile] = Field(
        default_factory=list,
        description="Generated or modified files.",
    )