"""
Planning domain models.

These models represent the structured implementation plan generated by the
planning stage of the CodePilot AI pipeline.
"""

from typing import List

from pydantic import BaseModel, Field


class Plan(BaseModel):
    """
    Structured implementation plan generated by the planning stage.
    """

    goal: str = Field(
        ...,
        description="Overall implementation goal.",
    )

    relevant_files: List[str] = Field(
        default_factory=list,
        description="Files that should be read or modified.",
    )

    implementation_steps: List[str] = Field(
        default_factory=list,
        description="Implementation steps.",
    )

    risks: List[str] = Field(
        default_factory=list,
        description="Potential implementation risks.",
    )

    testing: List[str] = Field(
        default_factory=list,
        description="Testing checklist.",
    )